package org.imagequiz.model;
// Generated Jun 20, 2013 3:43:04 AM by Hibernate Tools 3.2.1.GA



/**
 * Iqcase generated by hbm2java
 */
public class IQCaseDAO  implements java.io.Serializable {


     private Long id;
     private String casetext = "";
     private String questionxml = "";
     private String filename = "";

    public IQCaseDAO() {
    }

	
    public IQCaseDAO(String filename) {
        this.filename = filename;
    }
    public IQCaseDAO(String casetext, String questionxml, String filename) {
       this.casetext = casetext;
       this.questionxml = questionxml;
       this.filename = filename;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getCasetext() {
        return this.casetext;
    }
    
    public void setCasetext(String casetext) {
        this.casetext = casetext;
    }
    public String getQuestionxml() {
        return this.questionxml;
    }
    
    public void setQuestionxml(String questionxml) {
        this.questionxml = questionxml;
    }
    public String getFilename() {
        return this.filename;
    }
    
    public void setFilename(String filename) {
        this.filename = filename;
    }




}


